ln -s ./dotfiles/.vimrc ~/.vimrc ;
ln -s ./dotfiles/.vim ~/.vim ;
ln -s ./dotfiles/.zprofile ~/.zprofile ;
ln -s ./dotfiles/.aliases ~/.aliases ;
ln -s ./dotfiles/.zscript ~/.zscript ;
ln -s ./dotfiles/.zfunc ~/.zfunc ;
ln -s ./dotfiles/.zshrc ~/.zshrc ;
ln -s ./dotfiles/.gitconfig ~/.gitconfig ;
ln -s ./dotfiles/.gemrc ~/.gemrc ;
ln -s ./dotfiles/.agignore ~/.agignore ;
mkdir -p ~/.vim/bundle ;
cd /tmp ;
curl https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh > installer.sh ;
sh installer.sh ~/.vim/bundle ;
ssh-keygen -t ed25519 -N '' ;
cd ~/dotfiles/ ;
git clone git@github.com:mbadolato/iTerm2-Color-Schemes.git ;
